<?php
namespace
{
	set_include_path(__DIR__ . DIRECTORY_SEPARATOR . 'classes');
	spl_autoload_register('spl_autoload');
	if (! function_exists('php_check_syntax')) {
		/**
		* Check the PHP syntax of (and execute) the specified file
		*
		* @param  string $filename      The name of the file being checked.
		* @param  string $error_message The error message generated by the syntax check. (by reference)
		* @return bool                  Returns TRUE if the lint check passed, and FALSE if the link check failed
		*/
		function php_check_syntax($filename, &$error_message)
		{
			$out = [];
			$error_message = exec(sprintf('php -l %s', escapeshellarg($filename)), $out, $return_var);
			return $return_var !== false;
		}
	}
}
namespace Unit
{
	if (PHP_SAPI !== 'cli') {
		http_response_code(403);
		exit();
	}
	\shgysk8zer0\Core\NamespacedFunction::{'\Test_funcs\lint_scripts_recursive'}(__DIR__);
}
